"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.searchresults_get200_response_filters_fields_inner_options_inner import (
    SearchresultsGet200ResponseFiltersFieldsInnerOptionsInner,
)
from deutschland.klinikatlas.model.searchresults_get200_response_filters_fields_inner_slider_options_inner import (
    SearchresultsGet200ResponseFiltersFieldsInnerSliderOptionsInner,
)

from deutschland import klinikatlas

globals()[
    "SearchresultsGet200ResponseFiltersFieldsInnerOptionsInner"
] = SearchresultsGet200ResponseFiltersFieldsInnerOptionsInner
globals()[
    "SearchresultsGet200ResponseFiltersFieldsInnerSliderOptionsInner"
] = SearchresultsGet200ResponseFiltersFieldsInnerSliderOptionsInner
from deutschland.klinikatlas.model.searchresults_get200_response_filters_fields_inner import (
    SearchresultsGet200ResponseFiltersFieldsInner,
)


class TestSearchresultsGet200ResponseFiltersFieldsInner(unittest.TestCase):
    """SearchresultsGet200ResponseFiltersFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchresultsGet200ResponseFiltersFieldsInner(self):
        """Test SearchresultsGet200ResponseFiltersFieldsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchresultsGet200ResponseFiltersFieldsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
