"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.searchresults_get200_response_sortings_fields_inner_options_inner import (
    SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner,
)

from deutschland import klinikatlas


class TestSearchresultsGet200ResponseSortingsFieldsInnerOptionsInner(unittest.TestCase):
    """SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchresultsGet200ResponseSortingsFieldsInnerOptionsInner(self):
        """Test SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
