"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.searchresults_get200_response_sortings_fields_inner_options_inner import (
    SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner,
)

from deutschland import klinikatlas

globals()[
    "SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner"
] = SearchresultsGet200ResponseSortingsFieldsInnerOptionsInner
from deutschland.klinikatlas.model.searchresults_get200_response_sortings_fields_inner import (
    SearchresultsGet200ResponseSortingsFieldsInner,
)


class TestSearchresultsGet200ResponseSortingsFieldsInner(unittest.TestCase):
    """SearchresultsGet200ResponseSortingsFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchresultsGet200ResponseSortingsFieldsInner(self):
        """Test SearchresultsGet200ResponseSortingsFieldsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchresultsGet200ResponseSortingsFieldsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
