"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.searchresults_get200_response_filters import (
    SearchresultsGet200ResponseFilters,
)
from deutschland.klinikatlas.model.searchresults_get200_response_meta_infos import (
    SearchresultsGet200ResponseMetaInfos,
)
from deutschland.klinikatlas.model.searchresults_get200_response_results_inner import (
    SearchresultsGet200ResponseResultsInner,
)
from deutschland.klinikatlas.model.searchresults_get200_response_sortings import (
    SearchresultsGet200ResponseSortings,
)

from deutschland import klinikatlas

globals()["SearchresultsGet200ResponseFilters"] = SearchresultsGet200ResponseFilters
globals()["SearchresultsGet200ResponseMetaInfos"] = SearchresultsGet200ResponseMetaInfos
globals()[
    "SearchresultsGet200ResponseResultsInner"
] = SearchresultsGet200ResponseResultsInner
globals()["SearchresultsGet200ResponseSortings"] = SearchresultsGet200ResponseSortings
from deutschland.klinikatlas.model.searchresults_get200_response import (
    SearchresultsGet200Response,
)


class TestSearchresultsGet200Response(unittest.TestCase):
    """SearchresultsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchresultsGet200Response(self):
        """Test SearchresultsGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchresultsGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
