"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.fileadmin_json_german_places_json_get200_response_inner import (
    FileadminJsonGermanPlacesJsonGet200ResponseInner,
)

from deutschland import klinikatlas


class TestFileadminJsonGermanPlacesJsonGet200ResponseInner(unittest.TestCase):
    """FileadminJsonGermanPlacesJsonGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileadminJsonGermanPlacesJsonGet200ResponseInner(self):
        """Test FileadminJsonGermanPlacesJsonGet200ResponseInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileadminJsonGermanPlacesJsonGet200ResponseInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
