"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.searchresults_get200_response_filters_fields_inner import (
    SearchresultsGet200ResponseFiltersFieldsInner,
)

from deutschland import klinikatlas

globals()[
    "SearchresultsGet200ResponseFiltersFieldsInner"
] = SearchresultsGet200ResponseFiltersFieldsInner
from deutschland.klinikatlas.model.searchresults_get200_response_filters import (
    SearchresultsGet200ResponseFilters,
)


class TestSearchresultsGet200ResponseFilters(unittest.TestCase):
    """SearchresultsGet200ResponseFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchresultsGet200ResponseFilters(self):
        """Test SearchresultsGet200ResponseFilters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchresultsGet200ResponseFilters()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
