"""
    Bundes-Klinik-Atlas API

    Die API des Bundes-Klinik-Atlas stellt eine Vielzahl von Informationen über deutsche Kliniken und deren Ausstattung bereit.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: poststelle@bmg.bund.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.klinikatlas.model.searchresults_get200_response_meta_infos_search_arguments import (
    SearchresultsGet200ResponseMetaInfosSearchArguments,
)

from deutschland import klinikatlas


class TestSearchresultsGet200ResponseMetaInfosSearchArguments(unittest.TestCase):
    """SearchresultsGet200ResponseMetaInfosSearchArguments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchresultsGet200ResponseMetaInfosSearchArguments(self):
        """Test SearchresultsGet200ResponseMetaInfosSearchArguments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchresultsGet200ResponseMetaInfosSearchArguments()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
